# Generated by Django 4.2.21 on 2025-07-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoEscaneado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo_pdf', models.FileField(upload_to='examenes/')),
                ('texto_extraido', models.TextField(blank=True, null=True)),
                ('fecha_escaneo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
