# Generated by Django 4.2.21 on 2025-06-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M1_Gestion_de_Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dispositivousuario',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dispositivousuario',
            name='fingerprint',
            field=models.CharField(max_length=64),
        ),
    ]
