# Generated by Django 4.2.21 on 2025-06-25 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logos_universidades/')),
                ('especialidad', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_solucionario', models.CharField(choices=[('admision', 'Solucionario de Examen de Admisión'), ('ejercicios', 'Solucionario de Ejercicios'), ('otro', 'Otro')], default='admision', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.CharField(max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='examenes/')),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='M2_Contenido_Educativo.universidad')),
            ],
        ),
    ]
