# Generated by Django 4.2.21 on 2025-06-18 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('pais', models.CharField(default='Perú', max_length=100)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(upload_to='logos_universidades/')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.CharField(max_length=50)),
                ('archivo', models.FileField(upload_to='examenes/')),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='M2_CONTENIDO_EDUCATIVO.universidad')),
            ],
        ),
    ]
