# Generated by Django 4.2.21 on 2025-06-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M2_CONTENIDO_EDUCATIVO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='examenes/'),
        ),
    ]
