# Generated by Django 4.2.21 on 2025-06-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M2_CONTENIDO_EDUCATIVO', '0002_alter_examen_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='universidad',
            name='tipo_solucionario',
            field=models.CharField(choices=[('admision', 'Solucionario de Examen de Admisión'), ('ejercicios', 'Solucionario de Ejercicios'), ('otro', 'Otro')], default='admision', max_length=20),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='especialidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='pais',
            field=models.CharField(max_length=100),
        ),
    ]
