# Generated by Django 4.2.21 on 2025-07-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M2_CONTENIDO_EDUCATIVO', '0004_alter_universidad_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='miniatura',
            field=models.ImageField(blank=True, null=True, upload_to='miniaturas_examenes/'),
        ),
    ]
