# Generated by Django 4.2.21 on 2025-07-06 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('M2_CONTENIDO_EDUCATIVO', '0006_rename_especialidad_universidad_institucion_educativa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universidad',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='universidad',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='universidad',
            unique_together={('nombre', 'codigo_modular')},
        ),
    ]
