# Generated by Django 4.2.21 on 2025-07-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('M2_CONTENIDO_EDUCATIVO', '0007_alter_universidad_options_universidad_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universidad',
            old_name='docente_creador',
            new_name='profesor_creador',
        ),
    ]
