# Generated by Django 4.2.21 on 2025-07-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M2_CONTENIDO_EDUCATIVO', '0008_rename_docente_creador_universidad_profesor_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='universidad',
            name='curso',
            field=models.CharField(blank=True, choices=[('MAT', 'Matemática'), ('COM', 'Comunicación'), ('CTA', 'Ciencia, Tecnología y Ambiente'), ('PER', 'Persona, Familia y Relaciones Humanas'), ('HIS', 'Historia'), ('GEO', 'Geografía'), ('CIV', 'Civismo'), ('RAZ', 'Razonamiento Verbal'), ('RM', 'Razonamiento Matemático'), ('TRI', 'Trigonometría'), ('ALG', 'Álgebra'), ('GEO2', 'Geometría'), ('ARI', 'Aritmética'), ('BIO', 'Biología'), ('QUI', 'Química'), ('FIS', 'Física'), ('ING', 'Inglés'), ('APT', 'Aptitud Académica'), ('OTR', 'Otro')], max_length=10, null=True),
        ),
    ]
