# Generated by Django 4.2.21 on 2025-07-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M2_CONTENIDO_EDUCATIVO', '0009_universidad_curso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universidad',
            options={'ordering': ['nombre'], 'verbose_name': 'Universidad/Repositorio', 'verbose_name_plural': 'Universidades/Repositorios'},
        ),
        migrations.AddField(
            model_name='universidad',
            name='carrera',
            field=models.CharField(blank=True, choices=[('ingenieria', 'Ingeniería'), ('administracion', 'Administración'), ('ciencias_sociales', 'Ciencias Sociales'), ('ciencias_de_la_salud', 'Ciencias de la Salud')], max_length=50, null=True, verbose_name='Carrera'),
        ),
        migrations.AddField(
            model_name='universidad',
            name='nivel',
            field=models.CharField(blank=True, choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('universitario', 'Universitario')], max_length=20, null=True, verbose_name='Nivel Académico'),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='curso',
            field=models.CharField(blank=True, choices=[('MAT', 'Matemática'), ('COM', 'Comunicación'), ('CTA', 'Ciencia, Tecnología y Ambiente'), ('PER', 'Persona, Familia y Relaciones Humanas'), ('HIS', 'Historia'), ('GEO', 'Geografía'), ('CIV', 'Civismo'), ('RAZ', 'Razonamiento Verbal'), ('RM', 'Razonamiento Matemático'), ('TRI', 'Trigonometría'), ('ALG', 'Álgebra'), ('GEO2', 'Geometría'), ('ARI', 'Aritmética'), ('BIO', 'Biología'), ('QUI', 'Química'), ('FIS', 'Física'), ('ING', 'Inglés'), ('APT', 'Aptitud Académica'), ('OTR', 'Otro')], max_length=10, null=True, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='logo',
            field=models.ImageField(upload_to='logos_universidades/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='pais',
            field=models.CharField(blank=True, choices=[('AF', 'Afganistán'), ('AL', 'Albania'), ('DE', 'Alemania'), ('AD', 'Andorra'), ('AO', 'Angola'), ('AG', 'Antigua y Barbuda'), ('SA', 'Arabia Saudita'), ('DZ', 'Argelia'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaiyán'), ('BS', 'Bahamas'), ('BD', 'Bangladés'), ('BB', 'Barbados'), ('BH', 'Baréin'), ('BE', 'Bélgica'), ('BZ', 'Belice'), ('BJ', 'Benín'), ('BY', 'Bielorrusia'), ('BO', 'Bolivia'), ('BA', 'Bosnia y Herzegovina'), ('BW', 'Botsuana'), ('BR', 'Brasil'), ('BN', 'Brunéi'), ('BG', 'Bulgaria'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('BT', 'Bután'), ('CV', 'Cabo Verde'), ('KH', 'Camboya'), ('CM', 'Camerún'), ('CA', 'Canadá'), ('QA', 'Catar'), ('TD', 'Chad'), ('CL', 'Chile'), ('CN', 'China'), ('CY', 'Chipre'), ('VA', 'Ciudad del Vaticano'), ('CO', 'Colombia'), ('KM', 'Comoras'), ('CG', 'Congo'), ('KP', 'Corea del Norte'), ('KR', 'Corea del Sur'), ('CI', 'Costa de Marfil'), ('CR', 'Costa Rica'), ('HR', 'Croacia'), ('CU', 'Cuba'), ('DK', 'Dinamarca'), ('DM', 'Dominica'), ('EC', 'Ecuador'), ('EG', 'Egipto'), ('SV', 'El Salvador'), ('AE', 'Emiratos Árabes Unidos'), ('ER', 'Eritrea'), ('SK', 'Eslovaquia'), ('SI', 'Eslovenia'), ('ES', 'España'), ('US', 'Estados Unidos'), ('EE', 'Estonia'), ('ET', 'Etiopía'), ('PH', 'Filipinas'), ('FI', 'Finlandia'), ('FJ', 'Fiyi'), ('FR', 'Francia'), ('GA', 'Gabón'), ('GM', 'Gambia'), ('GE', 'Georgia'), ('GH', 'Ghana'), ('GD', 'Granada'), ('GR', 'Grecia'), ('GT', 'Guatemala'), ('GY', 'Guyana'), ('GN', 'Guinea'), ('GQ', 'Guinea Ecuatorial'), ('GW', 'Guinea-Bisáu'), ('HT', 'Haití'), ('HN', 'Honduras'), ('HU', 'Hungría'), ('IN', 'India'), ('ID', 'Indonesia'), ('IQ', 'Irak'), ('IR', 'Irán'), ('IE', 'Irlanda'), ('IS', 'Islandia'), ('IL', 'Israel'), ('IT', 'Italia'), ('JM', 'Jamaica'), ('JP', 'Japón'), ('JO', 'Jordán'), ('KZ', 'Kazajistán'), ('KE', 'Kenia'), ('KG', 'Kirguistán'), ('KI', 'Kiribati'), ('KW', 'Kuwait'), ('LA', 'Laos'), ('LS', 'Lesoto'), ('LV', 'Letonia'), ('LB', 'Líbano'), ('LR', 'Liberia'), ('LY', 'Libia'), ('LI', 'Liechtenstein'), ('LT', 'Lituania'), ('LU', 'Luxemburgo'), ('MK', 'Macedonia del Norte'), ('MG', 'Madagascar'), ('MY', 'Malasia'), ('MW', 'Malaui'), ('MV', 'Maldivas'), ('ML', 'Mali'), ('MT', 'Malta'), ('MA', 'Marruecos'), ('MU', 'Mauricio'), ('MR', 'Mauritania'), ('MX', 'México'), ('FM', 'Micronesia'), ('MD', 'Moldavia'), ('MC', 'Mónaco'), ('MN', 'Mongolia'), ('ME', 'Montenegro'), ('MZ', 'Mozambique'), ('MM', 'Myanmar'), ('NA', 'Namibia'), ('NR', 'Nauru'), ('NP', 'Nepal'), ('NI', 'Nicaragua'), ('NE', 'Níger'), ('NG', 'Nigeria'), ('NO', 'Noruega'), ('NZ', 'Nueva Zelanda'), ('OM', 'Omán'), ('NL', 'Países Bajos'), ('PK', 'Pakistán'), ('PW', 'Palaos'), ('PA', 'Panamá'), ('PG', 'Papúa Nueva Guinea'), ('PY', 'Paraguay'), ('PE', 'Perú'), ('PL', 'Polonia'), ('PT', 'Portugal'), ('GB', 'Reino Unido'), ('CF', 'República Centroafricana'), ('CZ', 'República Checa'), ('CD', 'República Democrática del Congo'), ('DO', 'República Dominicana'), ('RW', 'Ruanda'), ('RO', 'Rumania'), ('RU', 'Rusia'), ('WS', 'Samoa'), ('KN', 'San Cristóbal y Nieves'), ('SM', 'San Marino'), ('VC', 'San Vicente y las Granadinas'), ('LC', 'Santa Lucía'), ('ST', 'Santo Tomé y Príncipe'), ('SN', 'Senegal'), ('RS', 'Serbia'), ('SC', 'Seychelles'), ('SL', 'Sierra Leona'), ('SG', 'Singapur'), ('SY', 'Siria'), ('SO', 'Somalia'), ('LK', 'Sri Lanka'), ('ZA', 'Sudáfrica'), ('SD', 'Sudán'), ('SS', 'Sudán del Sur'), ('SE', 'Suecia'), ('CH', 'Suiza'), ('SR', 'Surinam'), ('TH', 'Tailandia'), ('TZ', 'Tanzania'), ('TJ', 'Tayikistán'), ('TL', 'Timor Oriental'), ('TG', 'Togo'), ('TO', 'Tonga'), ('TT', 'Trinidad y Tobago'), ('TN', 'Túnez'), ('TM', 'Turkmenistán'), ('TR', 'Turquía'), ('TV', 'Tuvalu'), ('UA', 'Ucrania'), ('UG', 'Uganda'), ('UY', 'Uruguay'), ('UZ', 'Uzbekistán'), ('VU', 'Vanuatu'), ('VE', 'Venezuela'), ('VN', 'Vietnam'), ('YE', 'Yemen'), ('DJ', 'Yibuti'), ('ZM', 'Zambia'), ('ZW', 'Zimbabue')], max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='tipo_solucionario',
            field=models.CharField(choices=[('admision', 'Solucionario de Examen de Admisión'), ('ejercicios', 'Solucionario de Ejercicios'), ('otro', 'Otro')], default='admision', max_length=50, verbose_name='Tipo de Repositorio'),
        ),
    ]
