# Generated by Django 4.2.21 on 2025-07-10 22:16

import M2_CONTENIDO_EDUCATIVO.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M2_CONTENIDO_EDUCATIVO', '0010_alter_universidad_options_universidad_carrera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='archivo',
            field=models.FileField(blank=True, null=True, storage=M2_CONTENIDO_EDUCATIVO.storage.ExamenesUniversidadesStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='logo',
            field=models.ImageField(storage=M2_CONTENIDO_EDUCATIVO.storage.LogosUniversidadesStorage(), upload_to='', verbose_name='Logo'),
        ),
    ]
